openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Jam Session API'
  description: Search for Artists or Songs
servers:
  - url: 'localhost:5000'
    description: local server (dev)
paths:
  /spotify/getCredentials:
    get:
      summary: Gets Spotify Credentials
      parameters:
        - name: Content-Type
          description: Content-Type setting
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/ContentType'
      responses:
        '200':
          description: Credentials successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
        400:
          description: User details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: No Credentials were created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /spotify/search:
    get:
      parameters:
        - name: q
          description: search query
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/SearchQuery'
        - name: type
          description: type of items to search for 
          in: query
          schema:
            $ref: '#/components/schemas/SearchType'
        - name: Authorization
          description: spotify Credentials
          in: header
          required: true
          schema:
            $ref: '#components/securitySchemes/bearerAuth'
      responses:
        '200':
          description: Search successful return list/s
          content:
            application/json:
              schema:
                $ref: '#/components/schema/SearchLists'
        400:
          description: Search endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Search was not completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ContentType:
        type: string
    Credentials:
      type: object
      required:
        - access_token
        - token_type
    SearchQuery:
      type: string
    SearchType:
      type: string
      enum:
        - artist
        - track
    SearchLists:
      type: object
      properties:
        data:
          type: object
          properties:
            artists:
              type: object
            tracks:
              type: object
      required:
        - data
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    bearerAuth:      
      type: http
      scheme: bearer
security:
  - securitySchemes: []